## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Cabañas Francisco Javier | Cochrane"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  facebook = "https://facebook.com"
  email = "gauchita.velasquez@gmail.com"
  phone = "+56940398910"
  instagram = "https://instagram.com"